---
title: "Global Equitable Oxford: what are our research and teaching responsibilities to the wider world? (Oxford Talks)"
date: 2023-11-08
categories:
    - events
---

What responsibilities should Oxford researchers and teachers have towards people around the world? How inclusive should we be of people not physically based in Oxford or the UK? This panel explores what a global approach to EDI should mean for our University’s core research and education mission. How can we build capacity among people able to make a difference in their own communities? How should we work with groups with relevant lived experience around the world? What obligations do we have to build a sustainable legacy within the countries and regions within which we undertake research? In order to reflect on these questions, this panel draws upon the experience of three different research programmes from different disciplinary perspectives, each with a shared approach to globally inclusive research, covering conservation, modelling, and refugee-led research.

Speaker details: Professor E.J. Milner-Gulland (Department of Biology), **Professor Lisa White (Department of Biology)**, Andonis Marden (Refugees Studies Centre)

[Event link](https://talks.ox.ac.uk/talks/id/9a9067bb-794f-4750-a5d7-e8a0ca57c811/)