---
title: "Interviews with the Health Experts of Bangladesh: A Brief Insight into the COVID-19 Situation in Dhaka"
date: 2021-11-30
categories:
    - news
    - interviews
---

In recent years, medical narratives have been proposed as a model for humane and effective medical practices and have played a more prevalent role in scientific research during the last decade. COVID-19 has had no shortage of medical narratives, the most shocking being from citizens in rural settings. I talked with Mofakhar Hussain, a medical doctor from Bangladesh, currently living in Toronto, Canada:

**Q:** What has your personal story been during the COVID-19 pandemic? Give any kind of details you feel comfortable sharing.

**A:** “My mom is 75 years old and she was isolated in Bangladesh due to COVID-19. This was horrible from our perspective because she was living alone. We were constantly in touch with her to make sure she was isolating and not coming into contact with people. After a couple of months, my sister who lives in New York and my brother who lives in Connecticut whose wife works as a schoolteacher, were affected. My brother’s wife got COVID and was admitted to hospital, the following day he was too. The children, 12 and 5, had to be left alone at home and could not come into contact with other people. This was a harrowing situation for us, especially tricky in the early days. I was talking to the nurse at the hospital three times a day to make sure my brother was stable and improving and he was at 90 percent oxygen. My brother-in-law would park outside in his car and sleep outside the house to make sure the kids were ok as well as leaving food outside for the kids. At the same time, we were talking to my mother, calming her down and reassuring her that we would survive the trauma. After two weeks, my brother and his wife were okay and were discharged from the hospital. Eventually they got the vaccine. We had two doctors in Bangladesh check on my mother to make sure she was ok. My wife’s mother is also around that same age, also alone in Bangladesh. My mom calls her mother twice a day to make sure she is okay. My mother-in-law also takes care of her brother who is 78, and is diagnosed with autism. There is a sort of bearing, mental strength associated with the extended period. This will have an impact for times to come as this trauma will result in an extended recovery time. Every family knows someone in their own family or close to them who has suffered. This is a story that has happened a hundred times over – the moral of the story needs to be told for us to understand the impact.”

**Q:** How did it affect your country?

**A:** “In Bangladesh, the situation was pretty bad. The death rate is about 24 percent right now. We had about three waves, we are now in the third wave. The first wave was urban-based, the disease spread within urban environments from people who came from outside the country and airports. The third wave is caused by neighbouring people from India coming into Bangladesh and carrying the delta variant. The delta variant is spreading fast and the worry is that it will spread into the urban setting. About 9 million have been affected and about 14,000 have died. Infection is a relatively low number but we are still in the early stages. The stay at home order was issued from July 1st, shutdown and registration has not necessarily worked in the past but we shall see how it will work now. Bangladesh started with the AZ vaccine from the institute in India. That delivery of the vaccine has now been stalled due to the circumstances in India. India has stopped exporting the vaccine as they will use them for themselves. Bangladesh will likely get vaccination imports from China and maybe some Pfizer from the US. Vaccinations will likely not be the solution for Bangladesh. Schools have been closed since March 2020 and have no plans to reopen. There are industries like the garment centre which have remained open. The government announced some disbursement. People are thinking that the poverty rate will double. What is more worrying is the loss of the education rate for many people. Medicine requires education for society to advance. More than a year of school closure means the loss of education for our children. One, people are simply not learning. Second, as many people are not going to school, people are doing something else and drop out. Many children may be selling or peddling on the streets. Third, the rate of child marriage has increased. This is very dangerous as we are losing girls (women are the anchor of society). Say for example the father of a family has become poor, he has a 12/13-year-old daughter, someone makes them an offer, he takes this money to survive. This child becomes pregnant in the next year, may or may not survive, or faces a number of medical problems in the future.”

**Q:** What were some of your specific pandemic procedures and quarantine rules?

**A:** “The government has all kinds of rules that they post on their website. Most people (30-50 percent) get their information from the internet. Lately there are TV and radio announcements. In Bangladesh, people use microphones to announce isolation, the same thing they do with tornadoes/cyclones.”

**Q:** How do you think the pandemic and school closures have affected girls and education?

**A:** “We are losing girls in the education system. The majority of the people that are dying are males (60 percent). However, the people that have been negatively affected are women. The education system tries to bring women to equality. When this system is not working it puts women behind. We have increased deaths, poverty, child marriages and mental health issues which all affect women. We know that being out of school makes people distressed from being out of school for so long, and we do not know what the severe mental health impacts will be.”

The situation remains dire in Bangladesh; travellers are advised to avoid travel to the country, and anyone who arrives in the country must be fully vaccinated. Dr Shafiun Shimul, a resident of Dhaka and member of the Public Health Advisory Committee gave more information on government intervention and research:

**Q:** What kind of research has your team been doing throughout the pandemic?

**A:** “When the first case of COVID was reported in March 2020, I was following everything in the US on international news. I was also following the news in the US because I resided in Nebraska for 6 years and also Italy. I was looking at all the expert comments and stories. I assumed it was coming to Bangladesh because we had no border control. Nobody checked my temperature at the airport, there was some intervention where I had to declare if I was experiencing symptoms or if I had been to China. People very much panicked when the first case was detected in Bangladesh. The case rate went up and the first announcement I remember was on 18 March. Then came some prediction modelling by many organisations including John Hopkins. In Bangladesh, the Public Health Advisory Committee was formed to administer the eight divisions in Bangladesh. I was part of the N-95 mask ignition. Using Python code, I found a model I could use that predicted that Bangladesh would have 50,000 cases by the end of May 2020 even though we only had 2000 cases at that time, which told me that the situation in
Bangladesh would be very bad. Obviously, it was very hard to develop intervention in developing countries because of a lack of income. DGHS, a department in the Ministry of Health and Family Welfare in Bangladesh, shared this information from the model with the Prime Minister. This is basically how the prediction journey started. I was hosting that projection modelling on my personal webpage. My journey started with an intention to do something for the country and I figured out that no one was striking an intervention in Bangladesh, so it was my part to help. I tried to use my economic and mathematical knowledge to help, even though I am not an infectious disease modeller. We then switched to modelling with the CoMo Consortium. I also had a chapter published on free government COVID testing.”

**Q:** How about personally? How was your family affected by the pandemic?

**A:** “My father-in-law and mother-in-law were both affected. My father-in-law was in the ICU for quite some time and is still in hospital. My mother-in-law also tested positive but was in our home and in isolation for quite some time. My three kids were away for two weeks at my sister’s house so that they could stay clear of the virus as my wife and I were visiting the COVID hospital almost every day. My wife and I did have COVID symptoms last year and in August. However, it was quite difficult to get tested. My doctor advised me to stay at home. My uncle died due to COVID two days ago. I have also seen many relatives affected, including my colleague’s relatives. Bangladesh is now experiencing a very difficult time with COVID due to our limited testing. Every day we have around 50,000 new cases and our testing is around 5000 a day, which is very limited compared to other countries. Bangladesh is now under lockdown until the 5th of August.”

**Q:** How did the government respond initially to the pandemic crisis?

**A:** “I always tried to follow the lockdown rules especially because of the widespread vaccine hesitancy. It was very hard at first because the kids had to be kept away from their mom as she had to visit her father in the hospital. It was very hard especially because the living conditions in Dhaka are not ideal as everything is very crowded and dense in population. The government had measures to check how closely procedures were being followed. Strict lockdowns are heavily enforced. For three days you can see on Google that rules are being followed, but after a couple of days, people start following regulations loosely. Industry will be open on August 1st. The government could not remain strict for an extended period of time and has tried sporadically, it has been highly disorganised and inconsistent; it was practically impossible for the government to say that the infections would be solved in a week. The government also has taken a lot of contradictory steps, which is not helpful for compliance. They also did not make a priority of the virus itself, rather policy priorities lay in economics.”

Bangladesh has faced many hardships over the past year; deep diving into the country’s experience, the shadow of COVID-19 is especially reflected on the youth, specifically the impact of mental stress on themselves and their families. Sarah Farheen Khan, Programme Assistant at ICCAD and a resident of Dhaka, gave information regarding her research on the topic:

**Q:** How would you describe the mental stress impact on the youth situation in Bangladesh?

**A:** “COVID has of course affected us mentally and physically. Especially for young people, drug abuse has increased a good amount. Substance abuse, especially marijuana has increased, in which the youth has not really been interested in learning anymore. Overeating, especially with fast food, has increased, especially because of the lack of exercise. The sleep cycle has changed completely, young people have been using the internet, watching movies, and apps like TikTok more at night. The amount of time they are looking at screens has increased a very large amount. The financial crisis has affected us a large amount. Also, the amount of violence has increased which of course has affected the mental state of young people; they are seeing their mothers, sisters, fathers affected. TikTok has increased this violence because people will do crazy things to be recognised. Families have not been able to provide their family with smart devices because of the financial crisis, which has especially been harrowing since everything has shifted to a virtual level. Using apps like WhatsApp, Facebook, and Twitter is how we connect these days. The rise of unemployment has increased; many people have lost their jobs due to organisations going bankrupt.”

**Q:** In terms of education, how have women in Dhaka and other parts of the country been affected?

**A:** “Child marriages have increased. The legal age of marriage is 18 but parents will often marry off their daughters at the age of 13 and 14. The purpose is it is considered as having less of a burden. Parents prefer their sons to be educated and not their daughters if they can only afford to send one child to school. Women being murdered has also increased during this pandemic due to the large amount of domestic abuse. This is a very common scenario happening in Dhaka and it makes it harder for things to change due to this being so normalised in parts of Bangladesh. Women can call 999-111 for help, which is an initiative Bangladesh is taking to counter domestic violence.”

Listening to everybody’s stories, it’s quite clear that although they are all citizens of Bangladesh, the pandemic tells a different story for everybody. While some were directly impacted, seeing close family members struggle through the crisis, some only had friends and distant relatives impacted. While this remains true on a global scale, Bangladesh has especially been hit hard in the area of education. As of now, schools remain closed with no plans to reopen, leading to negative labour market performances resulting from a financial crisis. And though the pandemic has died down for some countries, rural countries like Bangladesh continue to live through the biggest healthcare frenzy of our generation.

COVID stories remain one of the biggest interests for narrative medicine right now. Not only have they been used as a plea for public health and for the unification of communities, but they serve as a reminder that tough days are far from over. Bangladesh is certainly not the only country which remains in a state of mass crisis, and if we are to move forward through the pandemic as a global community, we must re-evaluate our outlook during this crucial time.

**Interviewer:** **Ananya Chag** is an article contributor/intern for the University of Oxford. A high school senior and aspiring journalist at Porter-Gaud School, Charleston, South Carolina, Ananya works with Tracy Evans, Communications Officer for the CoMo Consortium, to produce “a human face” to the COVID-19 situation in Bangladesh.