project:
  type: website
  output-dir: _site

website:
  title: ""
  site-url: https://como-international.github.io

  page-footer:
    center: Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
    right: "&copy; 2020-2024 &middot; CoMo Consortium"

  navbar:
    title: false
    # logo: img/CoMo-logo-medium-white_resized.png
    logo: img/como_inter_dark.png
    logo-alt: "CoMo Consortium"
    href: https://como-international.github.io
    search: true
    background: "#00214d" # oxford blue
    # background: "#0a2b57" # 25% lighter
    # background: "#ddd"
    left:
      - href: index.qmd
        text: Home
      - text: "Research"
        menu:
        - publications.qmd
        - models.qmd
        # - research.qmd
      - training.qmd
      - news.qmd
      - text: "About"
        menu:
        - about.qmd
        - team.qmd
        - participating_countries.qmd
        - contact.qmd

format:
  html:
    theme: [flatly, styles/custom.scss]
    toc: true
    toc-location: left
