project:
  type: website
  output-dir: _site

website:
  title: ""
  site-url: https://como-international.github.io
  favicon: img/favicon.png
  google-analytics: "G-CKG6D2B9DS"

  page-footer:
    center: Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
    right: "&copy; 2020-2024 &middot; CoMo International"
  
  twitter-card: 
    site: "@ComoConsortium"

  navbar:
    title: false
    # logo: img/CoMo-logo-medium-white_resized.png
    logo: img/como_inter_dark.png
    logo-alt: "CoMo International"
    href: https://como-international.github.io
    search: true
    background: "#002147" # university primary
    # background: "#00214d" # oxford blue
    # background: "#0a2b57" # 25% lighter
    # background: "#ddd"
    foreground: light
    left:
      - href: index.qmd
        text: "Home"
      - text: "Research"
        menu:
        - publications.qmd
        - models.qmd
        # - research.qmd
      - text: Training
        href: training/training.qmd
        # menu:
        # - href: training/training.qmd
        #   text: "Strategic Modelling for Public Health Policy Training Programme"
        # - href: training/training-r.qmd
        #   text: " - Introduction to R for Modellers"
        # - href: training/training-midc-intro.qmd
        #   text: " - Modelling Infectious Diseases in Context: Introduction"
        # - href: training/training-midc-inter.qmd
        #   text: " - Modelling Infectious Diseases in Context: Intermediate"
        
      - news.qmd
      - text: "About"
        menu:
        # - about.qmd
        # - team.qmd
        # - participating_countries.qmd
        - text: Contact
          href: contact.qmd
        - icon: twitter-x
          href: https://twitter.com/ComoConsortium
        - icon: github
          href: https://github.com/como-international

format:
  html:
    theme: [flatly, styles/custom.scss]
    toc: true
    toc-location: left
