---
title: "Interviews with Manar Marzouk, Global Health Researcher, Syria (North West and North East)"
date: 2021-12-01
categories:
    - news
    - interviews
---

A decade-long civil war has crippled Syria’s healthcare system: the country now has four healthcare systems with limited interaction and communication between them and the small number of hospitals are struggling to cope with the Covid-19 pandemic. There is low capacity for testing; mask wearing and social distancing are problematic – this, after all, is a warzone; and cases of Covid-19 are increasing. With large numbers of displaced persons – North West Syria has 2.6 million internally displaced people out of a population of 4.2 million, a healthcare system devastated by bombardment, limited humanitarian access, continued conflict and an economy in turmoil, Syria is particularly vulnerable to the effects of the virus.

Manar Marzouk is a global health researcher with a focus on health policy and health systems in refugee and conflict settings. In 2016 she left her home and work with Unicef in Syria to study for a Master’s in International Health at the University of Oxford.

In addition to her position as a researcher at the London School of Hygiene and Tropical Medicine, Manar is working with the COVID-19 International Modelling Consortium (CoMo), modelling the impact of COVID-19 mitigation measures in different regions in Syria.

**Q:** Manar, what brought you to CoMo?

**A:** I learned about CoMo through Oxford’s alumni network – in April 2020, I attended a presentation of a new model developed by a team of public health researchers and mathematical modellers at the University of Oxford to analyse the impact of policy interventions on the pandemic.

At that time, there hadn’t been any cases of COVID-19 reported in Syria but there was concern that the disease would have a huge negative impact in displacement settings – in North West Syria there are almost 3.2 million internally displaced persons and in North East Syria around 900,000.

Although there are many models available world-wide, I favoured using the CoMo model as the framework is based on a participatory approach and close collaboration with policymakers – this is crucial in a setting where the health governance is fragmented and there is limited public data available. Also, the continuous support provided by the technical team and other members within the consortium is invaluable as is the exchange of knowledge and expertise with modellers in low- and middle-resource settings.

**Q:** How did you set up the teams?

**A:** We have two modelling groups in Syri**a:** one for the North West of Syria and one for the North East.

In May 2020, I presented the CoMo model to policymakers in North West Syria and, through snowballing, I formed a team of six local health experts. The team includes the Director of the Health Information System Unit for North West Syria (HIS), the CEO of the Relief Experts Association (UDER), the Coordinator of the Early Warning Alert and Response Network/Assistance Coordination Unit (EWARN), the Coordinator at the American Relief Coalition for Syria, and a clinician at Bab Al-Hawa Hospital.

In November 2020, we established the COVID-19 modelling group for North East Syria. This collaborates with the Kurdish Red Crescent and Self Administration health authority – the latter provided us with access to COVID-19 cases and mortality figures while the task force helped in contextualizing the parameters in accordance with the context of North East Syria. 

**Q:** Tell me a bit about the work you do?

**A:** My work is primarily with the local CoMo team in North West Syria. The policymaking process is fragmented in North West Syria following years of conflict but we are successfully engaging with policymakers in the health and education sector. We have presented our findings to the National and International Task Force and we have addressed questions from the Interim Ministry of Health regarding the impact on the epidemic of opening schools. The CoMo modelling findings are used by NGOs, such as UDER, as a tool for advocacy for increasing the coverage of wearing face masks in Northwest Syria.

**Q:** What are your main challenges?

**A:** COVID-19 has helped us as modellers and public health practitioners to better understand the healthcare system in North West and North East Syria. Fragmented health governance and decision making was clear from our early discussions around parameters for the model: when we were thinking about scenarios and non-pharmaceutical interventions, we had to be mindful of who would be implementing COVID-19 measures. To help with this we created a process map for decision making – we ended up with over 10 decision makers with conflicting interests and priorities. 

Another challenge is the disempowerment of local healthcare actors. For example, when we started presenting our findings to the Ministry of Health, we were referred to external organisations such as the World Health Organisation, The United Nations Office for the Coordination of Humanitarian Affairs etc. for approval – local policymakers felt they didn’t have the power to implement any measures without approval from external donors.  

We have also noticed a pattern of prioritising no-cost interventions. School closure is one of the key interventions that we are requested to model as it is perceived as the least costly to implement but it is not without cost – indeed, in Syria’s context it can have a drastic impact on children’s development and protection.

**Q:** Why is modelling important in the Syrian setting?

**A:** Modelling supports the decision-making process by providing policymakers with evidence-based data so they can weigh the pros and cons of different mitigation measures. This is particularly important in situations where measures could have negative unintended consequences – with school closures for example. According to UNCIEF over 2.1 million children have dropped out of school since the start of conflict in Syria. Modelling enables policymakers to weigh the impact of this type of intervention on both COVID-19 and children’s education. This is especially important in a society where being prevented from attending school could expose children to risks of recruitment in armed groups, domestic violence and early child marriage.

Another important example is that modelling enables us to project the impact of COVID-19 on hospital occupancy. This is crucial in limited settings – the health system in Syria is functioning on half, if not less, of its capacity and modelling has help us to predict the trajectory of infections and the likely number of hospitalisations which is crucial information in limited settings.

**Q:** What achievements are you and your team most proud of?

**A:** There have been other models used within Syria during to project the impact of COVID-19 on the Syrian healthcare system but to my knowledge, our modelling teams are the only ones working in close contact with local policymakers and health staff in the field. 

What has been heartening is that the modelling we’ve been doing has created a common ground for different conflicting parties. It has enabled us to simulate different scenarios using a combination of non-pharmaceutical interventions such as an international travel ban, school closure, handwashing, facemask wearing, social distancing, and working from home. Having the data that we can demonstrate visually to policymakers has enabled us to have meetings to present findings and these have been followed by discussions to improve the model inputs. It has been so rewarding to see policymakers use the findings for strategic planning: the findings from our modelling influenced the annual strategy plan for the COVID-19 task force in North East Syria and the health minister of the interim government used our outputs in his public engagement.

Modelling is a new concept in many countries including Syria. Establishing the modelling team in North West Syria has helped our team members to develop their capacity in modelling and evidence synthesis. It has given us the ability to combine scientific evidence relating to the COVID-19 pandemic with model projections and to present findings to policymakers and external donors. The team’s knowledge has been further enriched through sharing of knowledge through the participatory nature of CoMo and through interaction with teams in other countries such as Bangladesh, Kyrgyzstan, Afghanistan and Iran.

**Q:** What are your hopes for modelling in Syria?

**A:** I am passionate about building the capacity of local health staff in modelling. Before the pandemic there weren’t many Syrians with skills in mathematical and pandemic modelling. COVID-19 has given us the opportunity to develop a skill base within the country and I’d like to see it develop further still as it will be crucial not only to see out the pandemic but also in supporting efforts to mitigate other infectious disease beyond COVID-19. 

We also hope that through our modelling work we will be able to use the CoMo model to build common ground for Syria’s four health systems. So far, we have managed to go some way to establishing this in the North West and North East Syria. 

If we could continue with the trajectory we’ve established – building our modelling capacity, establishing common ground for our healthcare systems, continuing to engage with policymakers and drive through change, bringing the strengths of collaboration and participation and knowledge exchange to the way we work – Syria would be in much better position to countenance the healthcare challenges of its present and future.

Manar Marzouk is a global health researcher with a focus on health policy and health systems in refugee and conflict settings. In addition to her position as a researcher at the London School of Hygiene and Tropical Medicine, she is currently working with the COVID-19 International Modelling Consortium (CoMo) at the University of Oxford, modelling the impact of COVID-19 mitigation measures in different regions in Syria. She is also involved in several projects on health systems and policy analysis in different countries in the MENA region, including UNESCWA – The National Agenda for the Future of Syria (NAFS Programme), Lebanon Support – The Right to Health in Lebanon and Jordan, and UNICEF/Valid International – CMAM Evaluation in Sudan. She has previously worked on cancer care management for Syrian refugees in Jordan (WHO-EMRO, 2016), and minorities’ experiences in accessing mental health services (Health Experience Research Group, University of Oxford, 2017), and has over 7 years’ field experience in the humanitarian sector in Syria and the UK (Valid International, 2018-20; Asylum Welcome, 2016-2018; UNICEF, 2014-2015; UNHCR, 2013-2014). She holds a Master’s in International Health and Tropical Medicine from the University of Oxford, and a bachelor’s degree in Pharmacy from the University of Damascus.

**Interviewer:** **Tracy Evans** is the communications lead for the CoMo project. Tracy has over 20 years’ experience of delivering strategic integrated marketing and communications activities and programmes for global brands. As Communications Officer for the CoMo Consortium, Tracy leads communications activity, both on and offline, and works with the team to drive and deliver the outreach and dissemination activities, engaging both in-country experts and policymakers and translating findings from the consortium into learnings that can be used for policy decision making.